// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

func init() { proto.RegisterFile("event.proto", fileDescriptor_event_f5a6adc94e79be06) }

var fileDescriptor_event_f5a6adc94e79be06 = []byte{
	// 58 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x2d, 0x4b, 0xcd,
	0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0x4a, 0x4d, 0xc9, 0xaf, 0x70, 0xe2,
	0x8a, 0xe2, 0x00, 0xf3, 0x93, 0xf3, 0x73, 0x92, 0xd8, 0xc0, 0x2c, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xa9, 0x46, 0x3a, 0x9b, 0x28, 0x00, 0x00, 0x00,
}
